### ISSUE TITLE
ToDo: Graphics

### ISSUE THREAD

**Issue by automainint** [automainint/quadwar#2]
- [ ] Rendering
  - [x] [LCh[ab]](https://en.wikipedia.org/wiki/CIELAB_color_space#CIEHLC_cylindrical_model) color.
  - [ ] Text: bit font and [TrueType](https://github.com/nothings/stb/blob/master/stb_truetype.h).
  - [ ] Basic UI elements: button, panel, text area.
  - [ ] Solid objects.
  - [ ] Object selection.
  - [ ] Lighting and materials.
  - [ ] Depth maps: shadows, transparency.
  - [ ] Flat reflective surfaces.
  - [ ] Cubic maps: reflection and refraction.
  - [ ] Volumetrics.
  - [ ] Animation.
  - [ ] Particles.
- [ ] Data conversion
  - [ ] Export model data from [Blender](https://www.blender.org/) to C code. [Example](https://gist.github.com/automainint/3db01180fd591f0a7ea18032290aa146)
  - [ ] Convert images to C code.
