### ISSUE TITLE
ToDo: Gameplay

### ISSUE THREAD

**Issue by automainint** [automainint/quadwar#3]
- [x] Setup [kit](https://github.com/automainint/kit) for basic utilities.
- [ ] Setup [laplace](https://github.com/automainint/laplace) and [eval](https://github.com/automainint/eval) for the deterministic engine framework.
- [ ] Setup [peer](https://github.com/automainint/peer) for networking.
- [ ] Implement basic RTS features.
